# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"http://{default}/":
    type: upstream
    upstream: "php:http"
    cache:
        enabled: true
        headers: [ "Accept", "Accept-Language", "X-Language-Locale" ]
        cookies: ["*"]
        default_ttl: 60

"http://{default}/admin":
    type: upstream
    upstream: "php:http"
    cache:
        enabled: false

"http://www.{default}/":
    type: redirect
    to: "http://{default}/"
